cinema_bo:
    resource: "@CinemaBoBundle/Resources/config/routing.yml"
    prefix:   /administration

app:
    resource: @AppBundle/Controller/
    type:     annotation
cinema_bo_login:
    path:     /users/signin
    defaults: { _controller: CinemaBoBundle:Users:signin}
cinema_bo_login_check:
    path:     /administration/users/logincheck
    defaults: { _controller: CinemaBoBundle:Users:signin}
cinema_bo_Logout:
    path:     /administration/users/logout
    defaults: { _controller: CinemaBoBundle:Users:logout}
cinema_bo_denied:
    path:     /administration/users/denied
    defaults: { _controller: CinemaBoBundle:Users:denied}
cinema_bo_user_autologin:
    path:     /users/autologin/{login}
    defaults: { _controller: CinemaBoBundle:Users:autologin,login: saadna }