cinema_bo:
    resource: "@CinemaBoBundle/Resources/config/routing.yml"
    prefix:   /administration

app:
    resource: @AppBundle/Controller/
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
cinema_bo_login:
    path:     /login
    defaults: { _controller: CinemaBoBundle:Users:signin}
cinema_bo_login_check:
    path:     /administration/users/logincheck
    defaults: { _controller: CinemaBoBundle:Users:signin}
cinema_bo_Logout:
    path:     /administration/users/logout
    defaults: { _controller: CinemaBoBundle:Users:logout}
cinema_bo_denied:
    path:     /administration/users/denied
    defaults: { _controller: CinemaBoBundle:Users:denied}
cinema_bo_user_autologin:
    path:     /users/autologin/{login}
    defaults: { _controller: CinemaBoBundle:Users:autologin,login: saadna }

#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api
