security:
    encoders:
            FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username
    firewalls:
            # disables authentication for assets and the profiler, adapt it according to your needs
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false
            main:
                pattern:    ^/administration
                form_login:
                    provider: fos_userbundle
                    csrf_provider: form.csrf_provider
                    check_path: cinema_bo_login_check
                    login_path: cinema_bo_login
                    #default_target_path: cinema_bo_login
                logout:
                    path:   cinema_bo_Logout
                    target: cinema_bo_login
                #anonymous: ~
                #http_basic:
                #    realm: "Secured Demo Area"


    access_denied_url:  cinema_bo_denied



    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/users, roles: ROLE_SUPER_ADMIN}
        - { path: ^/administration, roles: ROLE_ADMIN}

