# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html

security:
    providers:
        administrators:
            entity: { class: Cinema\BoBundle\Entity\User, property: username }

    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    access_denied_url:  cinema_bo_denied
    encoders:
        Cinema\BoBundle\Entity\User:
                    algorithm:        sha1
                    encode_as_base64: false
                    iterations:       1

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # the login page has to be accessible for everybody

        # secures part of the application
        admin_secured_area:
            pattern:    ^/administration
            # it's important to notice that in this case _demo_security_check and _demo_login
            # are route names and that they are specified in the AcmeDemoBundle
            form_login:
                check_path: cinema_bo_login_check
                login_path: cinema_bo_login
            logout:
                path:   cinema_bo_Logout
                target: cinema_bo_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^/signin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/administration, roles: ROLE_ADMIN}

