cinema_bo:
    path:     /bo
    defaults: { _controller: CinemaBoBundle:Default:index }
cinema_bo_contact:
    path:     /bo/contact
    defaults: { _controller: CinemaBoBundle:Default:contact }
cinema_bo_blank:
    path:     /bo/blank
    defaults: { _controller: CinemaBoBundle:Default:blank }
cinema_bo_MentionsLegales:
    path:     /bo/mentionslegales
    defaults: { _controller: CinemaBoBundle:Static:mentionslegales }
cinema_bo_cgu:
    path:     /bo/cgu
    defaults: { _controller: CinemaBoBundle:Static:cgu }
cinema_bo_MentionsLegales:
    path:     /bo/credits
    defaults: { _controller: CinemaBoBundle:Static:credit }
cinema_bo_Apropos:
    path:     /bo/apropos
    defaults: { _controller: CinemaBoBundle:Static:apropos }
cinema_bo_test:
    path:     /bo/test
    defaults: { _controller: CinemaBoBundle:Static:test }
cinema_bo_movies:
    path:     /bo/movies
    defaults: { _controller: CinemaBoBundle:Movies:listMovies }
cinema_bo_movies_new:
    path:     /bo/movies/new
    defaults: { _controller: CinemaBoBundle:Movies:newMovie }
cinema_bo_movie_remove:
    path:     /bo/movie/remove/{id}
    defaults: { _controller: CinemaBoBundle:Movies:removeMovie }
    requirements:
            id: \d+
cinema_bo_movie_edit:
    path:     /bo/movie/edit/{id}
    defaults: { _controller: CinemaBoBundle:Movies:editMovie }
    requirements:
            id: \d+
cinema_bo_movies_best:
    path:     /bo/bestmovies
    defaults: { _controller: CinemaBoBundle:Movies:getBestMovies }
cinema_bo_movies_bestExpected:
    path:     /bo/bestexpectedmovies
    defaults: { _controller: CinemaBoBundle:Movies:getBestExpectedMovies }
cinema_bo_movie:
    path:     /bo/movie/{id}
    defaults: { _controller: CinemaBoBundle:Movies:getMovie }
    requirements:
            id: \d+
cinema_bo_movies_category:
    path:     /bo/movies/category/{catId}
    defaults: { _controller: CinemaBoBundle:Movies:listMoviesByCategory }
    requirements:
            catId: \d+
cinema_bo_categories:
    path:     /bo/categories
    defaults: { _controller: CinemaBoBundle:Categories:getCategories }
cinema_bo_movies_tag:
    path:     /bo/movies/tag/{tagId}
    defaults: { _controller: CinemaBoBundle:Movies:listMoviesByTag }
    requirements:
            catId: \d+
cinema_bo_Tags:
    path:     /bo/tags
    defaults: { _controller: CinemaBoBundle:Categories:getTags}
cinema_bo_actor:
    path:     /bo/actor/{id}
    defaults: { _controller: CinemaBoBundle:Actors:getActor}
    requirements:
            id: \d+
cinema_bo_Actors:
    path:     /bo/actors
    defaults: { _controller: CinemaBoBundle:Actors:getActors}
cinema_bo_director:
    path:     /bo/director/{id}
    defaults: { _controller: CinemaBoBundle:Directors:getDirector}
    requirements:
            id: \d+
cinema_bo_Directors:
    path:     /bo/directors
    defaults: { _controller: CinemaBoBundle:Directors:getDirectors}
cinema_bo_Seances:
    path:     /bo/seances
    defaults: { _controller: CinemaBoBundle:Seances:getSeances}
cinema_bo_Cinemas:
    path:     /bo/cinemas
    defaults: { _controller: CinemaBoBundle:Cinemas:getCinemas}
cinema_bo_Comments:
    path:     /bo/comments
    defaults: { _controller: CinemaBoBundle:Cinemas:getComments}
cinema_bo_Sessions:
    path:     /bo/sessions
    defaults: { _controller: CinemaBoBundle:Sessions:getSessions}