cinema_bo:
    path:     /
    defaults: { _controller: CinemaBoBundle:Default:index }
cinema_bo_contact:
    path:     /contact
    defaults: { _controller: CinemaBoBundle:Default:contact }
cinema_bo_blank:
    path:     /blank
    defaults: { _controller: CinemaBoBundle:Default:blank }
cinema_bo_MentionsLegales:
    path:     /mentionslegales
    defaults: { _controller: CinemaBoBundle:Static:mentionslegales }
cinema_bo_cgu:
    path:     /cgu
    defaults: { _controller: CinemaBoBundle:Static:cgu }
cinema_bo_MentionsLegales:
    path:     /credits
    defaults: { _controller: CinemaBoBundle:Static:credit }
cinema_bo_Apropos:
    path:     /apropos
    defaults: { _controller: CinemaBoBundle:Static:apropos }
cinema_bo_test:
    path:     /test
    defaults: { _controller: CinemaBoBundle:Static:test }
cinema_bo_movies:
    path:     /movies
    defaults: { _controller: CinemaBoBundle:Movies:listMovies }
cinema_bo_movies_new:
    path:     /movies/new
    defaults: { _controller: CinemaBoBundle:Movies:newMovie }
cinema_bo_movie_remove:
    path:     /movie/remove/{id}
    defaults: { _controller: CinemaBoBundle:Movies:removeMovie }
    requirements:
            id: \d+
cinema_bo_movie_edit:
    path:     /movie/edit/{id}
    defaults: { _controller: CinemaBoBundle:Movies:editMovie }
    requirements:
            id: \d+
cinema_bo_movies_best:
    path:     /bestmovies
    defaults: { _controller: CinemaBoBundle:Movies:getBestMovies }
cinema_bo_movies_bestExpected:
    path:     /bestexpectedmovies
    defaults: { _controller: CinemaBoBundle:Movies:getBestExpectedMovies }
cinema_bo_movie:
    path:     /movie/{id}
    defaults: { _controller: CinemaBoBundle:Movies:getMovie }
    requirements:
            id: \d+
cinema_bo_movies_category:
    path:     /movies/category/{catId}
    defaults: { _controller: CinemaBoBundle:Movies:listMoviesByCategory }
    requirements:
            catId: \d+
cinema_bo_categories:
    path:     /categories
    defaults: { _controller: CinemaBoBundle:Categories:getCategories }
cinema_bo_movies_tag:
    path:     /movies/tag/{tagId}
    defaults: { _controller: CinemaBoBundle:Movies:listMoviesByTag }
    requirements:
            catId: \d+
cinema_bo_Tags:
    path:     /tags
    defaults: { _controller: CinemaBoBundle:Categories:getTags}
cinema_bo_actor:
    path:     /actor/{id}
    defaults: { _controller: CinemaBoBundle:Actors:getActor}
    requirements:
            id: \d+
cinema_bo_Actors:
    path:     /actors
    defaults: { _controller: CinemaBoBundle:Actors:getActors}
cinema_bo_director:
    path:     /director/{id}
    defaults: { _controller: CinemaBoBundle:Directors:getDirector}
    requirements:
            id: \d+
cinema_bo_Directors:
    path:     /directors
    defaults: { _controller: CinemaBoBundle:Directors:getDirectors}
cinema_bo_Seances:
    path:     /seances
    defaults: { _controller: CinemaBoBundle:Seances:getSeances}
cinema_bo_Cinemas:
    path:     /cinemas
    defaults: { _controller: CinemaBoBundle:Cinemas:getCinemas}
cinema_bo_Comments:
    path:     /comments
    defaults: { _controller: CinemaBoBundle:Cinemas:getComments}
cinema_bo_Sessions:
    path:     /sessions
    defaults: { _controller: CinemaBoBundle:Sessions:getSessions}
cinema_bo_users_new:
    path:     /users/new
    defaults: { _controller: CinemaBoBundle:Registration:register}
cinema_bo_user_edit:
    path:     /users/edit/{id}
    defaults: { _controller: CinemaBoBundle:Users:editUser }
    requirements:
            id: \d+
cinema_bo_users:
    path:     /users
    defaults: { _controller: CinemaBoBundle:Users:getUsers}
