cinema_bo_homepage:
    path:     /hello/{name}
    defaults: { _controller: CinemaBoBundle:Default:index }
cinema_bo_contact:
    path:     /contact
    defaults: { _controller: CinemaBoBundle:Default:contact }
cinema_bo_blank:
    path:     /blank
    defaults: { _controller: CinemaBoBundle:Default:blank }
cinema_bo_MentionsLegales:
    path:     /mentionslegales
    defaults: { _controller: CinemaBoBundle:Static:mentionslegales }
cinema_bo_cgu:
    path:     /cgu
    defaults: { _controller: CinemaBoBundle:Static:cgu }
cinema_bo_MentionsLegales:
    path:     /credits
    defaults: { _controller: CinemaBoBundle:Static:credit }
cinema_bo_Apropos:
    path:     /apropos
    defaults: { _controller: CinemaBoBundle:Static:apropos }
cinema_bo_test:
    path:     /test
    defaults: { _controller: CinemaBoBundle:Static:test }
cinema_bo_movies:
    path:     /movies
    defaults: { _controller: CinemaBoBundle:Movies:listMovies }
cinema_bo_movie:
    path:     /movie/{id}
    defaults: { _controller: CinemaBoBundle:Movies:getMovie }
    requirements:
            id: \d+
cinema_bo_movie_remove:
    path:     /movie/remove/{id}
    defaults: { _controller: CinemaBoBundle:Movies:removeMovie }
    requirements:
            id: \d+
cinema_bo_movies_category:
    path:     /movies/category/{catId}
    defaults: { _controller: CinemaBoBundle:Movies:listMoviesByCategory }
    requirements:
            catId: \d+
cinema_bo_categories:
    path:     /categories
    defaults: { _controller: CinemaBoBundle:Categories:getCategories }