services:
#    cinema_bo.example:
#        class: Cinema\BoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    cinema.contactForm:
        class: Cinema\BoBundle\Form\ContactType
        tags:
            - { name: form.type,alias: contact}

    security.access.blacklist_voter:
        class:      Cinema\BoBundle\Security\Authorization\Voter\ClientIpVoter
        arguments:  [@service_container, [127.0.0.2, 171.171.171.171]]
        public:     false
        tags:
            -       { name: security.voter }
    bobundle_user.registration.form:
            class: Cinema\BoBundle\Form\RegistrationFormType
            tags:
                - { name: form.type, alias: bobundle_user_registration }

     #test service
    movie:
        class:  Cinema\BoBundle\Movie\Movie
        arguments:
            - 6
            - @doctrine.orm.entity_manager
