Medias:
    type: entity
    table: medias
    indexes:
        movies_id:
            columns:
                - movies_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nature:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        picture:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        video:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        movies:
            targetEntity: Movies
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movies_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
